--- 
 - name : copy install zookeeper
   template : src=install-zookeeper.sh.j2 dest=/root/ambari-install/install-zookeeper.sh mode=0755

 - name : run install zookeeper
   command : creates=/root/ambari-install/install-zookeeper.done /root/ambari-install/install-zookeeper.sh
