---
- hosts: hdp2
  vars:
     dns_server : 10.179.0.164
  user: root
  tasks :
  - name : Copy HDP repo
    action: copy src=files/hdp-release-2.0.0.2-1.el6.noarch.rpm dest=/tmp/hdp-release-2.0.0.2-1.el6.noarch.rpm
  - name : install HDP repo
    action: shell yum localinstall -y /tmp/hdp-release-2.0.0.2-1.el6.noarch.rpm creates=/etc/yum.repos.d/hdp.repo
  - name : install hadoop
    action: yum name=hadoop,hadoop-hdfs,hadoop-libhdfs,hadoop-yarn,hadoop-mapreduce,hadoop-client,openssl state=latest
  - name : install compression library
    action: yum name=snappy,snappy-devel,lzo,lzo-devel,hadoop-lzo,hadoop-lzo-native   state=latest
