- hosts: all
  user : root
  roles:
   - prereq
   - commons

- hosts: ambari_server
  user : root
  roles:
   - ambari-server
   - hdfs
   - yarn
   - mapreduce2
   - ganglia
   - nagios
   - zookeeper
   - hive
   - hcatalog
   - hbase
   - pig
   - webhcat
