- hosts: all
  user : root
  roles:
   - prereq
   - commons

- hosts: ambari_server
  user : root
  roles:
   - ambari-server

- hosts: all
  user : root
  roles:
   - ambari-agent

- hosts: ambari_server
  user : root
  roles:
   - blueprint

