#- hosts: all
#  user : root
#  roles:
#   - commons
#   - prereq

- hosts: namenode
  user : root
  roles:
  - namenode

- hosts: secondary_namenode
  user : root
  roles:
  - secondary_namenode

- hosts: nodemanager
  user : root
  roles:
  - nodemanager

- hosts: datanodes
  user : root
  roles:
  - datanodes

