- hosts: all
  user : root
  roles:
   - prereq
   - commons

- hosts: ambari_server
  user : root
  roles:
   - ambari-server

- hosts: namenode
  user : root
  roles:

- hosts: secondary_namenode
  user : root
  roles:

- hosts: resourcemanager
  user : root
  roles:

- hosts: datanodes
  user : root
  roles:
