--- 
 - name : install ambari-server
   yum : name=ambari-server state=present

 - name : configure ambari-server
   shell : ambari-server setup -j /usr/java/default -s  

 - name : start ambari-server
   service : name=ambari-server state=started enabled=yes

 - name : copy python script
   template : src=create-cluster.py.j2 dest=/tmp/create-cluster.py mode=0755
