--- 
 - name : install ambari-server
   yum : name=ambari-server state=present

 - name : Create Folder
   file : dest=/root/ambari-install state=directory mode=0755

 - name : Copy configs.sh
   copy : src=configs.sh dest=/root/ambari-install/configs.sh mode=0755

 - name : configure ambari-server
   command : creates=/root/ambari-install/ansible.done ambari-server setup -j /usr/java/default -s

 - name : start ambari-server
   service : name=ambari-server state=started enabled=yes

 - name : copy script
   template : src=create-cluster.sh.j2 dest=/root/ambari-install/create-cluster.sh mode=0755

 - name : create cluster
   command : creates=/root/ambari-install/create-cluster.done /root/ambari-install/create-cluster.sh
