---
# Install hadoop RPM
  - name : install hadoop
    action: yum name=hadoop,hadoop-hdfs,hadoop-libhdfs,hadoop-yarn,hadoop-mapreduce,hadoop-client,openssl state=latest
# Install compression RPM
  - name : install compression library
    action: yum name=snappy,snappy-devel,lzo,lzo-devel,hadoop-lzo,hadoop-lzo-native state=latest

# Create Directory
  - name : create log direcotory for HDFS
    file : path={{ item }} state=directory owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755 recurse=true
    with_items : hadoop.HDFS_LOG_DIR
  - name : create log direcotory for YARN
    file : path={{ item }} state=directory owner={{ hadoop.YARN_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755 recurse=true
    with_items : hadoop.YARN_LOG_DIR
  - name : create pid direcotory for HDFS
    file : path={{ item }} state=directory owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755 recurse=true
    with_items : hadoop.HDFS_PID_DIR
  - name : create pid direcotory for YARN
    file : path={{ item }} state=directory owner={{ hadoop.YARN_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755 recurse=true
    with_items : hadoop.YARN_PID_DIR
