--- 
 - include: user.yml

 - name : configure ambari repository
   copy : src=ambari.repo dest=/etc/yum.repos.d/ambari.repo

 - name : install ambari-agent
   yum : name=ambari-agent

 - name : configure ambari-agent
   template : src=ambari-agent.ini.j2 dest=/etc/ambari-agent/conf/ambari-agent.ini

 - name : start ambari-agent
   service : name=ambari-agent state=started enabled=yes
