--- 
 - include: user.yml

 - name : configure ambari repository
   copy : src=ambari.repo dest=/etc/yum.repos.d/ambari.repo
   when : not repository.local_repo

 - name : configure local repository
   template : src=ambari.repo.j2 dest=/etc/yum.repos.d/ambari.repo
   when : repository.local_repo
