---
  - name : remove link /etc/hadoop/conf
    file : path=/etc/hadoop/conf state=absent
  - name : change permission on /etc/hadoop/conf
    file : path=/etc/hadoop/conf owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy core-site.xml
    action : template src=core-site.xml.j2 dest=/etc/hadoop/conf/core-site.xml owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy hdfs-site.xml
    action : template src=hdfs-site.xml.j2 dest=/etc/hadoop/conf/hdfs-site.xml owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy yarn-site.xml
    action : template src=yarn-site.xml.j2 dest=/etc/hadoop/conf/yarn-site.xml owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy capacity-scheduler.xml
    action : template src=yarn-site.xml.j2 dest=/etc/hadoop/conf/yarn-site.xml owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy capacity-scheduler.xml
    action : copy src=hadoop_conf/capacity-scheduler.xml dest=/etc/hadoop/conf/capacity-scheduler.xml owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy commons-logging.properties
    action : copy src=hadoop_conf/commons-logging.properties dest=/etc/hadoop/conf/commons-logging.properties owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy container-executor.cfg
    action : copy src=hadoop_conf/container-executor.cfg dest=/etc/hadoop/conf/container-executor.cfg owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy hadoop-env.sh
    action : copy src=hadoop_conf/hadoop-env.sh dest=/etc/hadoop/conf/hadoop-env.sh owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
#  - name : copy hadoop-env.sh in profile.d
    action : copy src=hadoop_conf/hadoop-env.sh dest=/etc/profile.d/hadoop-env.sh mode=0755
  - name : copy hadoop-metrics2.properties
    action : copy src=hadoop_conf/hadoop-metrics2.properties dest=/etc/hadoop/conf/hadoop-metrics2.properties owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy hadoop-metrics2.properties-GANGLIA
    action : copy src=hadoop_conf/hadoop-metrics2.properties-GANGLIA dest=/etc/hadoop/conf/hadoop-metrics2.properties-GANGLIA owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy hadoop-policy.xml
    action : copy src=hadoop_conf/hadoop-policy.xml dest=/etc/hadoop/conf/hadoop-policy.xml owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy health_check
    action : copy src=hadoop_conf/health_check dest=/etc/hadoop/conf/health_check owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy log4j.properties
    action : copy src=hadoop_conf/log4j.properties dest=/etc/hadoop/conf/log4j.properties owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
  - name : copy yarn-env.sh
    action : copy src=hadoop_conf/yarn-env.sh dest=/etc/hadoop/conf/yarn-env.sh owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755
