---
# Install pre-requisite for a RS instance
  - name : Install requirements for switching off SElinux
    raw : yum -y install libselinux-python

  - name : Disable SELinux 
    selinux : state=disabled
    notify : 
    - turn it off

  - name : turn off iptables
    service : name=iptables state=stopped enabled=false

  - name : install ntp
    yum : name=ntp state=latest

  - name : configure ntp
    template : src=ntp.conf.j2 dest=/etc/ntp.conf
    notify : restart ntp

  - name : start ntp
    service: name=ntpd state=started enabled=true

  - name : copy jdk
    copy : src=jdk-7u45-linux-x64.rpm dest=/tmp/jdk-7u45-linux-x64.rpm mode=0644 force=no

  - name : install jdk
    yum : name=/tmp/jdk-7u45-linux-x64.rpm state=present

  - name : Add JAVA_HOME to user profile
    copy : src=java.sh dest=/etc/profile.d/java.sh 

  - name : install screen
    yum : name=screen state=latest
  
  - name : install screen
    yum : name=screen state=latest

# Create Hadoop Directory structure
  - name : create directories
    file : dest={{ hdp['dfs_datanode_data_dir'] }} state=directory
    file : dest={{ hdp['dfs_namenode_checkpoint_dir'] }} state=directory
    file : dest={{ hdp['dfs_namenode_name_dir'] }} state=directory
    file : dest={{ hdp['yarn_nodemanager_local-dirs'] }} state=directory
    file : dest={{ hdp['yarn_nodemanager_log-dirs'] }} state=directory
