--- 
 - name : copy yarn-site.json
   template : src=yarn-site.json.j2 dest=/root/ambari-install/yarn-site.json mode=0644

 - name : copy capacity-scheduler.json
   copy : src=capacity-scheduler.json dest=/root/ambari-install/capacity-scheduler.json mode=0644

 - name : copy install yarn
   template : src=install-yarn.sh.j2 dest=/root/ambari-install/install-yarn.sh mode=0755

 - name : run install yarn
   command : creates=/root/ambari-install/install-yarn.done /root/ambari-install/install-yarn.sh
