- name: restart ambari-server
  service: name=ambari-server state=restarted

- name: check if ambari-server is up
  wait_for: host={{ hostvars[groups['ambari_server'][0]]['ansible_fqdn'] }} port=8080 delay=10
