---
  - name: Create Secondray Namenode Directory 
    file : path={{ item }} state=directory owner={{ hadoop.HDFS_USER }} group={{ hadoop.HADOOP_GROUP }} mode=0755 recurse=true
    with_items : hadoop.FS_CHECKPOINT_DIR
  - name : Copy start up secondary namenode script
    action : template src=hadoop-secondarynamenode.j2 dest=/etc/init.d/hadoop-secondarynamenode mode=0755 owner=root group=root
